export const histories = [
  {
    data_id: 1,
    user_id: 1,
    time: 0,
    temp: 36.5,
    defecation: "普通",
    eat: "いつもと同じ",
    date: "2023-11-28",
    medicine_morning: true,
    medicine_afternoon: false,
    medicine_night: false,
    condition: "嘔吐しました",
    user_firstName: "太郎",
    user_lastName: "田中",
  },
  {
    data_id: 2,
    user_id: 2,
    time: 1,
    temp: 37.0,
    defecation: "軟便",
    eat: "7割",
    date: "2023-11-27",
    medicine_morning: false,
    medicine_afternoon: true,
    medicine_night: false,
    condition: "ぐったりしてます",
    user_firstName: "二郎",
    user_lastName: "田中",
  },
  {
    data_id: 3,
    user_id: 3,
    time: 2,
    temp: 37.5,
    defecation: "下痢",
    eat: "5割",
    date: "2023-11-26",
    medicine_morning: false,
    medicine_afternoon: false,
    medicine_night: false,
    condition: "けいれんしてます",
    user_firstName: "花子",
    user_lastName: "高橋",
  },
];
